"""Provider adapters and HTTP clients for retrieval services."""

from .adapters import (
    crossref_work_to_paper,
    datacite_work_to_paper,
    openalex_work_to_paper,
    semanticscholar_paper_to_paper,
)
from .clients import (
    SEMANTICSCHOLAR_DEFAULT_FIELDS,
    BaseHttpClient,
    ClientError,
    CrossrefClient,
    CrossrefWork,
    DataCiteClient,
    DataCiteWork,
    ForbiddenError,
    GrobidClient,
    NotFoundError,
    OpenAccessLocation,
    OpenAlexClient,
    OpenAlexWork,
    RateLimitedError,
    RequestRejectedError,
    SemanticScholarClient,
    SemanticScholarPaper,
    UnauthorizedError,
    UnpaywallClient,
    UnpaywallFullTextCandidate,
    UnpaywallRecord,
    UpstreamError,
)

__all__ = [
    "crossref_work_to_paper",
    "datacite_work_to_paper",
    "openalex_work_to_paper",
    "semanticscholar_paper_to_paper",
    "BaseHttpClient",
    "ClientError",
    "CrossrefClient",
    "CrossrefWork",
    "DataCiteClient",
    "DataCiteWork",
    "GrobidClient",
    "NotFoundError",
    "OpenAccessLocation",
    "OpenAlexClient",
    "OpenAlexWork",
    "RateLimitedError",
    "RequestRejectedError",
    "SEMANTICSCHOLAR_DEFAULT_FIELDS",
    "SemanticScholarClient",
    "SemanticScholarPaper",
    "UnauthorizedError",
    "UnpaywallClient",
    "UnpaywallFullTextCandidate",
    "UnpaywallRecord",
    "ForbiddenError",
    "UpstreamError",
]
